class StudentAdditional {
  String phoneNumber;
  String birthday;
  String city;
  String street;
  String houseNumber;
  String apartmentNumber;
  String fatherName;
  String fatherSurname;
  String fatherPatronim;
  String fatherPhoneNumber;
  String fatherOrganization;
  String fatherPosition;
  String motherName;
  String motherSurname;
  String motherPatronim;
  String motherPhoneNumber;
  String motherOrganization;
  String motherPosition;
  bool isOrphan;
  bool areParentsDivorced;
  bool isFromLowIncomeFamily;
  bool isRaisedBySingleParent;
  bool isFromLargeFamily;
  bool isAffectedByChernobyl;
  bool areParentsCombatVeterans;
  bool isTemporarilyDisplaced;
  bool isDisabled;

  StudentAdditional({
    required this.phoneNumber,
    required this.birthday,
    required this.city,
    required this.street,
    required this.houseNumber,
    required this.apartmentNumber,
    required this.fatherName,
    required this.fatherSurname,
    required this.fatherPatronim,
    required this.fatherPhoneNumber,
    required this.fatherOrganization,
    required this.fatherPosition,
    required this.motherName,
    required this.motherSurname,
    required this.motherPatronim,
    required this.motherPhoneNumber,
    required this.motherOrganization,
    required this.motherPosition,
    required this.isOrphan,
    required this.areParentsDivorced,
    required this.isFromLowIncomeFamily,
    required this.isRaisedBySingleParent,
    required this.isFromLargeFamily,
    required this.isAffectedByChernobyl,
    required this.areParentsCombatVeterans,
    required this.isTemporarilyDisplaced,
    required this.isDisabled,
  });
}
